<div data-bind="scope: 'custom-scope'">
    <button data-bind="click: toggleState">Toggle state</button>
    <!-- ko if: isActive -->
        <div data-bind="mageInit: {'Vendor_Module/js/script': {}}">is active</div>
    <!-- /ko -->
</div>


<script type="text/x-magento-init">
        {
          "*": {
               "Magento_Ui/js/core/app": {
                    "components": {
                        "custom-scope": {
                            "component": "Vendor_Module/js/view/custom"
                        }
                    }
                }
            }
        }
</script>
