<div data-bind="scope: 'custom-scope'">
    <span data-bind="text: text"></span>
</div>


<script type="text/x-magento-init">
        {
          "*": {
               "Magento_Ui/js/core/app": {
                    "components": {
                        "custom-scope": {
                            "component": "Vendor_Module/js/view/custom"
                        }
                    }
                }
            }
        }
</script>
