<div data-bind="scope: 'custom-scope'">
    <!-- ko template: getTemplate() -->
        Loading...
    <!-- /ko -->
</div>


<script type="text/x-magento-init">
        {
          "*": {
               "Magento_Ui/js/core/app": {
                    "components": {
                        "parent": {
                            "component": "uiComponent",
                            "children": {
                                "child": {
                                    "component": "uiComponent"
                                }
                            }
                        }
                    }
                }
            }
        }
</script>
